create table if not exists sales (
  id serial primary key,
  channel text not null,
  remote_id text not null,
  status text not null default '',
  created_at_remote text,
  buyer text not null default '',
  email text,
  phone text,
  payment text,
  shipping_method text,
  shipping_cost numeric,
  subtotal numeric,
  total numeric,
  currency text not null default 'GBP',
  item_count integer not null default 0,
  remarks text,
  address_json text,
  items_json text,
  paid_at text,
  shipped_at text,
  url text,
  pulled_at timestamptz not null default now(),
  unique (channel, remote_id)
);
